version: '3.8'

services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - metabase

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db
    volumes:
      - ./infra/metabase/metabase.db:/metabase.db

  nginx:
    build: ./infra/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
