# Generated by Django 3.1.7 on 2021-04-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointment",
            "0003_historicalappointment_historicalfollowup_historicalstate_historicaltimeslot",
        ),
        ("patient", "0003_auto_20210405_1716"),
        ("finance", "0003_historicalcredit_historicalpayment_historicalpaymentmode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credit",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("appointment", "patient")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentmode",
            unique_together={("title",)},
        ),
    ]
