# Generated by Django 3.1.7 on 2021-03-14 07:00

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("joining_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_created_by",
                        to="staff.staff",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.role",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_reports",
                        to="staff.staff",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_updated_by",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"status": 1},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_created_by",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"status": 1},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_updated_by",
                to="staff.staff",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_created_by",
                        to="staff.staff",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"status": 1},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.staff",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"status": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_updated_by",
                        to="staff.staff",
                    ),
                ),
            ],
        ),
    ]
