# Generated by Django 3.1.7 on 2021-04-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_auto_20210323_2113"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("title", "slug")},
        ),
    ]
