# Generated by Django 3.1.7 on 2021-05-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treatment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="difficulty",
            options={"verbose_name_plural": "Difficulty"},
        ),
        migrations.AlterModelOptions(
            name="expertise",
            options={"verbose_name_plural": "Expertise"},
        ),
        migrations.AlterModelOptions(
            name="regime",
            options={"verbose_name_plural": "Regime"},
        ),
    ]
