# Generated by Django 3.1.7 on 2021-04-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient",
            "0002_historicalpatient_historicalpatientdetail_historicalphonenumber",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("first_name", "last_name", "primary_contact")},
        ),
    ]
