# Generated by Django 3.1.7 on 2021-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_auto_20210422_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_numbers",
            field=models.ManyToManyField(
                blank=True, related_name="patients", to="patient.PhoneNumber"
            ),
        ),
    ]
